// This file is @generated by prost-build.
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(clippy::all)]
#![allow(rustdoc::all)]

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PushRequest {
    #[prost(message, repeated, tag = "1")]
    pub streams: ::prost::alloc::vec::Vec<Stream>,
}
impl ::prost::Name for PushRequest {
    const NAME: &'static str = "PushRequest";
    const PACKAGE: &'static str = "app.log.loki.lokipb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "app.log.loki.lokipb.v1.PushRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/app.log.loki.lokipb.v1.PushRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Stream {
    #[prost(string, tag = "1")]
    pub labels: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub entries: ::prost::alloc::vec::Vec<Entry>,
    #[prost(uint64, tag = "3")]
    pub hash: u64,
}
impl ::prost::Name for Stream {
    const NAME: &'static str = "Stream";
    const PACKAGE: &'static str = "app.log.loki.lokipb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "app.log.loki.lokipb.v1.Stream".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/app.log.loki.lokipb.v1.Stream".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Entry {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "2")]
    pub line: ::prost::alloc::string::String,
}
impl ::prost::Name for Entry {
    const NAME: &'static str = "Entry";
    const PACKAGE: &'static str = "app.log.loki.lokipb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "app.log.loki.lokipb.v1.Entry".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/app.log.loki.lokipb.v1.Entry".into()
    }
}