// This file is @generated by prost-build.
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(clippy::all)]
#![allow(rustdoc::all)]

/// core.Duty
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Duty {
    /// uint64
    #[prost(uint64, tag = "1")]
    pub slot: u64,
    /// core.DutyType
    #[prost(int32, tag = "2")]
    pub r#type: i32,
}
impl ::prost::Name for Duty {
    const NAME: &'static str = "Duty";
    const PACKAGE: &'static str = "core.corepb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "core.corepb.v1.Duty".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/core.corepb.v1.Duty".into()
    }
}
/// core.UnsignedDataSet
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnsignedDataSet {
    /// map\[core.PubKey\]core.UnsignedData
    #[prost(btree_map = "string, bytes", tag = "1")]
    pub set: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::bytes::Bytes,
    >,
}
impl ::prost::Name for UnsignedDataSet {
    const NAME: &'static str = "UnsignedDataSet";
    const PACKAGE: &'static str = "core.corepb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "core.corepb.v1.UnsignedDataSet".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/core.corepb.v1.UnsignedDataSet".into()
    }
}
/// core.ParSignedDataSet
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParSignedDataSet {
    /// map\[core.PubKey\]core.ParSignedData
    #[prost(btree_map = "string, message", tag = "1")]
    pub set: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ParSignedData,
    >,
}
impl ::prost::Name for ParSignedDataSet {
    const NAME: &'static str = "ParSignedDataSet";
    const PACKAGE: &'static str = "core.corepb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "core.corepb.v1.ParSignedDataSet".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/core.corepb.v1.ParSignedDataSet".into()
    }
}
/// core.ParSignedData
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ParSignedData {
    /// \[\]byte
    #[prost(bytes = "bytes", tag = "1")]
    pub data: ::prost::bytes::Bytes,
    /// core.Signature
    #[prost(bytes = "bytes", tag = "2")]
    pub signature: ::prost::bytes::Bytes,
    /// int
    #[prost(int32, tag = "3")]
    pub share_idx: i32,
}
impl ::prost::Name for ParSignedData {
    const NAME: &'static str = "ParSignedData";
    const PACKAGE: &'static str = "core.corepb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "core.corepb.v1.ParSignedData".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/core.corepb.v1.ParSignedData".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QbftMsg {
    #[prost(int64, tag = "1")]
    pub r#type: i64,
    #[prost(message, optional, tag = "2")]
    pub duty: ::core::option::Option<Duty>,
    #[prost(int64, tag = "3")]
    pub peer_idx: i64,
    #[prost(int64, tag = "4")]
    pub round: i64,
    #[prost(int64, tag = "6")]
    pub prepared_round: i64,
    #[prost(bytes = "bytes", tag = "8")]
    pub signature: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "11")]
    pub value_hash: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "12")]
    pub prepared_value_hash: ::prost::bytes::Bytes,
}
impl ::prost::Name for QbftMsg {
    const NAME: &'static str = "QBFTMsg";
    const PACKAGE: &'static str = "core.corepb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "core.corepb.v1.QBFTMsg".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/core.corepb.v1.QBFTMsg".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QbftConsensusMsg {
    /// msg is the message that we send
    #[prost(message, optional, tag = "1")]
    pub msg: ::core::option::Option<QbftMsg>,
    /// justification is the justifications from others for the message
    #[prost(message, repeated, tag = "2")]
    pub justification: ::prost::alloc::vec::Vec<QbftMsg>,
    /// values of the hashes in the messages
    #[prost(message, repeated, tag = "3")]
    pub values: ::prost::alloc::vec::Vec<::prost_types::Any>,
}
impl ::prost::Name for QbftConsensusMsg {
    const NAME: &'static str = "QBFTConsensusMsg";
    const PACKAGE: &'static str = "core.corepb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "core.corepb.v1.QBFTConsensusMsg".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/core.corepb.v1.QBFTConsensusMsg".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SniffedConsensusMsg {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Other consensus protocol messages can be added here
    #[prost(message, optional, tag = "2")]
    pub msg: ::core::option::Option<QbftConsensusMsg>,
}
impl ::prost::Name for SniffedConsensusMsg {
    const NAME: &'static str = "SniffedConsensusMsg";
    const PACKAGE: &'static str = "core.corepb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "core.corepb.v1.SniffedConsensusMsg".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/core.corepb.v1.SniffedConsensusMsg".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SniffedConsensusInstance {
    #[prost(message, optional, tag = "1")]
    pub started_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int64, tag = "2")]
    pub nodes: i64,
    #[prost(int64, tag = "3")]
    pub peer_idx: i64,
    #[prost(message, repeated, tag = "4")]
    pub msgs: ::prost::alloc::vec::Vec<SniffedConsensusMsg>,
    #[prost(string, tag = "5")]
    pub protocol_id: ::prost::alloc::string::String,
}
impl ::prost::Name for SniffedConsensusInstance {
    const NAME: &'static str = "SniffedConsensusInstance";
    const PACKAGE: &'static str = "core.corepb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "core.corepb.v1.SniffedConsensusInstance".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/core.corepb.v1.SniffedConsensusInstance".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SniffedConsensusInstances {
    #[prost(message, repeated, tag = "1")]
    pub instances: ::prost::alloc::vec::Vec<SniffedConsensusInstance>,
    #[prost(string, tag = "2")]
    pub git_hash: ::prost::alloc::string::String,
}
impl ::prost::Name for SniffedConsensusInstances {
    const NAME: &'static str = "SniffedConsensusInstances";
    const PACKAGE: &'static str = "core.corepb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "core.corepb.v1.SniffedConsensusInstances".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/core.corepb.v1.SniffedConsensusInstances".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParSigExMsg {
    #[prost(message, optional, tag = "1")]
    pub duty: ::core::option::Option<Duty>,
    #[prost(message, optional, tag = "2")]
    pub data_set: ::core::option::Option<ParSignedDataSet>,
}
impl ::prost::Name for ParSigExMsg {
    const NAME: &'static str = "ParSigExMsg";
    const PACKAGE: &'static str = "core.corepb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "core.corepb.v1.ParSigExMsg".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/core.corepb.v1.ParSigExMsg".into()
    }
}
/// PriorityResult defines a cluster wide priority result of the Prioritiser protocol.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriorityResult {
    #[prost(message, repeated, tag = "1")]
    pub msgs: ::prost::alloc::vec::Vec<PriorityMsg>,
    #[prost(message, repeated, tag = "2")]
    pub topics: ::prost::alloc::vec::Vec<PriorityTopicResult>,
}
impl ::prost::Name for PriorityResult {
    const NAME: &'static str = "PriorityResult";
    const PACKAGE: &'static str = "core.corepb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "core.corepb.v1.PriorityResult".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/core.corepb.v1.PriorityResult".into()
    }
}
/// PriorityMsg defines all the priorities and metadata of a single peer in the Prioritiser protocol.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriorityMsg {
    #[prost(message, optional, tag = "1")]
    pub duty: ::core::option::Option<Duty>,
    #[prost(message, repeated, tag = "2")]
    pub topics: ::prost::alloc::vec::Vec<PriorityTopicProposal>,
    #[prost(string, tag = "3")]
    pub peer_id: ::prost::alloc::string::String,
    #[prost(bytes = "bytes", tag = "4")]
    pub signature: ::prost::bytes::Bytes,
}
impl ::prost::Name for PriorityMsg {
    const NAME: &'static str = "PriorityMsg";
    const PACKAGE: &'static str = "core.corepb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "core.corepb.v1.PriorityMsg".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/core.corepb.v1.PriorityMsg".into()
    }
}
/// PriorityTopicProposal defines a single peers proposed priorities for a single topic in the Prioritiser protocol.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriorityTopicProposal {
    #[prost(message, optional, tag = "1")]
    pub topic: ::core::option::Option<::prost_types::Any>,
    #[prost(message, repeated, tag = "2")]
    pub priorities: ::prost::alloc::vec::Vec<::prost_types::Any>,
}
impl ::prost::Name for PriorityTopicProposal {
    const NAME: &'static str = "PriorityTopicProposal";
    const PACKAGE: &'static str = "core.corepb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "core.corepb.v1.PriorityTopicProposal".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/core.corepb.v1.PriorityTopicProposal".into()
    }
}
/// PriorityTopicResult defines the cluster wide resulting priorities for a
/// single topic in the Prioritiser protocol.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriorityTopicResult {
    #[prost(message, optional, tag = "1")]
    pub topic: ::core::option::Option<::prost_types::Any>,
    /// priorities are ordered by decreasing score, ties are broken by peer with lowest peer ID.
    #[prost(message, repeated, tag = "2")]
    pub priorities: ::prost::alloc::vec::Vec<PriorityScoredResult>,
}
impl ::prost::Name for PriorityTopicResult {
    const NAME: &'static str = "PriorityTopicResult";
    const PACKAGE: &'static str = "core.corepb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "core.corepb.v1.PriorityTopicResult".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/core.corepb.v1.PriorityTopicResult".into()
    }
}
/// PriorityScoredResult defines the cluster wide priority score in the Prioritiser protocol.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PriorityScoredResult {
    #[prost(message, optional, tag = "1")]
    pub priority: ::core::option::Option<::prost_types::Any>,
    #[prost(int64, tag = "2")]
    pub score: i64,
}
impl ::prost::Name for PriorityScoredResult {
    const NAME: &'static str = "PriorityScoredResult";
    const PACKAGE: &'static str = "core.corepb.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "core.corepb.v1.PriorityScoredResult".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "type.googleapis.com/core.corepb.v1.PriorityScoredResult".into()
    }
}